import { useState } from 'react';
import { setContentEnabled } from '../../api/admin';
import { adminError, button, input, useAdminData } from './adminData';
type Content={key:string;title:string;category:string;paths:string[];source:string;enabled:boolean};
export default function AdminContent(){
  const result=useAdminData<{items:Content[]}>('/admin/content');
  const [category,setCategory]=useState('All');const [search,setSearch]=useState('');const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('');
  async function toggle(item:Content){if(busy)return;setBusy(item.key);setError('');setMessage('');try{await setContentEnabled(item.key,!item.enabled);setMessage(`${item.title} is now ${item.enabled?'unavailable':'available'}. Existing progress is preserved.`);result.reload();}catch(error){setError(adminError(error));}finally{setBusy('');}}
  const items=result.data?.items.filter(item=>(category==='All'||category===item.category)&&item.title.toLowerCase().includes(search.toLowerCase())) ?? [];
  return <><p className="mb-5 max-w-3xl leading-7 text-gray-600">Manage availability of existing lessons, vocabulary, grammar, games, quizzes, and character study tools. Disabled items show an unavailable page; lesson prerequisites still apply when enabled. Content text and questions remain in the existing course source files.</p>
    <div className="mb-6 flex flex-wrap gap-4"><label className="min-w-48 flex-1 text-sm font-bold">Search content<input className={input} value={search} onChange={event=>setSearch(event.target.value)} placeholder="Find a lesson or activity"/></label><label className="text-sm font-bold">Category<select className={input} value={category} onChange={event=>setCategory(event.target.value)}>{['All',...new Set(result.data?.items.map(item=>item.category))].map(value=><option key={value}>{value}</option>)}</select></label><button className={button+' self-end'} disabled={result.loading||!!busy} onClick={result.reload}>Refresh</button></div>
    {(error||result.error)&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-red-800">{error||result.error}</p>}{message&&<p role="status" className="mb-4 rounded-xl bg-emerald-50 p-4 text-emerald-800">{message}</p>}{result.loading&&<p role="status">Loading content…</p>}
    <div className="mt-4 grid gap-4 xl:grid-cols-2">{items.map(item=><article key={item.key} className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">{item.category}</p><h2 className="mt-2 text-lg font-bold">{item.title}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.enabled?'bg-emerald-50 text-emerald-800':'bg-gray-100 text-gray-600'}`}>{item.enabled?'Available':'Unavailable'}</span></div><p className="mt-3 text-sm text-gray-500">{item.source}</p><div className="mt-5 flex flex-wrap gap-3"><button className={button} disabled={!!busy||result.loading} onClick={()=>void toggle(item)}>{busy===item.key?'Saving…':item.enabled?'Disable':'Enable'}</button><span className="self-center text-sm text-gray-500">Learner page: {item.paths[0]}</span></div></article>)}</div>{!result.loading&&!result.error&&!items.length&&<p className="p-6 text-gray-500">No content matches your search.</p>}
  </>;
}
