import { useState } from 'react';
import type { FormEvent } from 'react';
import { updateUser } from '../../api/admin';
import { adminError, button, card, input, useAdminData } from './adminData';
type User={id:number;username:string;email:string;role:'learner'|'admin';status:'active'|'suspended';created_at:string;last_login_at:string|null};
type Results={users:User[];total:number;page:number;pageSize:number};
export default function AdminUsers({currentId,rolesOnly=false}:{currentId:number;rolesOnly?:boolean}){
  const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [page,setPage]=useState(1);
  const result=useAdminData<Results>(`/admin/users?search=${encodeURIComponent(query)}&page=${page}`);
  const [selected,setSelected]=useState<User|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
  async function save(event:FormEvent){event.preventDefault();if(!selected||busy)return;setBusy(true);setError('');setMessage('');try{await updateUser(selected.id,{username:selected.username,email:selected.email,role:selected.role,status:selected.status});setSelected(null);setMessage('User updated. Role and suspension changes apply to subsequent requests.');result.reload();}catch(error){setError(adminError(error));}finally{setBusy(false);}}
  return <>
    {rolesOnly&&<section className={card+' mb-5'}><h2 className="text-xl font-bold">Role permissions</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><p><strong>Learner</strong><br/>Access learning tools and personal progress.</p><p><strong>Admin</strong><br/>Manage users, content availability, and system settings.</p></div><p className="mt-4 text-sm text-gray-500">Administrator access is checked on the server. You cannot suspend or demote your own account, and at least one active administrator must remain.</p></section>}
    <form className="mb-5 flex flex-wrap items-end gap-3" onSubmit={event=>{event.preventDefault();setQuery(search.trim());setPage(1);}}><label className="min-w-0 flex-1 text-sm font-bold">Search users<input className={input} value={search} onChange={event=>setSearch(event.target.value)} placeholder="Username or email" maxLength={100}/></label><button className={button} disabled={result.loading}>Search</button><button type="button" className={button} disabled={result.loading} onClick={result.reload}>Refresh</button></form>
    {(error||result.error)&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-red-800">{error||result.error}</p>}{message&&<p role="status" className="mb-4 rounded-xl bg-emerald-50 p-4 text-emerald-800">{message}</p>}
    {selected&&<form onSubmit={save} className={card+' mb-6'}><h2 className="text-xl font-bold">Edit {selected.username}</h2><fieldset disabled={busy} className="mt-5 grid gap-4 sm:grid-cols-2">
      {!rolesOnly&&<><label className="text-sm font-bold">Username<input required pattern="[A-Za-z0-9_]{3,30}" className={input} value={selected.username} onChange={event=>setSelected({...selected,username:event.target.value})}/></label><label className="text-sm font-bold">Email<input required type="email" maxLength={254} className={input} value={selected.email} onChange={event=>setSelected({...selected,email:event.target.value})}/></label></>}
      <label className="text-sm font-bold">Role<select disabled={selected.id===currentId} className={input} value={selected.role} onChange={event=>setSelected({...selected,role:event.target.value as User['role']})}><option value="learner">Learner</option><option value="admin">Admin</option></select></label>
      {!rolesOnly&&<label className="text-sm font-bold">Account status<select disabled={selected.id===currentId} className={input} value={selected.status} onChange={event=>setSelected({...selected,status:event.target.value as User['status']})}><option value="active">Active</option><option value="suspended">Suspended</option></select></label>}
      <p className="text-sm text-gray-500 sm:col-span-2">Suspension preserves learning progress and prevents authenticated access. Admins can change accounts and platform settings; assign this role only to trusted users.</p>
      <div className="flex gap-3 sm:col-span-2"><button className={button+' border-emerald-500 text-emerald-800'}>{busy?'Saving…':'Save changes'}</button><button type="button" className={button} onClick={()=>{setSelected(null);setError('');}}>Cancel</button></div>
    </fieldset></form>}
    {result.loading&&<p role="status" className="mb-4">Loading users…</p>}
    <div className="overflow-x-auto rounded-2xl border border-gray-200 bg-white"><table className="w-full text-left text-sm"><caption className="sr-only">User accounts</caption><thead className="bg-gray-50 text-gray-500"><tr>{['User','Role','Status','Last login','Action'].map(label=><th key={label} className="px-5 py-4">{label}</th>)}</tr></thead><tbody>{result.data?.users.map(user=><tr key={user.id} className="border-t border-gray-100"><td className="px-5 py-4"><p className="font-bold">{user.username}{user.id===currentId?' (you)':''}</p><p className="text-gray-500">{user.email}</p></td><td className="px-5 py-4 capitalize">{user.role}</td><td className="px-5 py-4 capitalize">{user.status}</td><td className="px-5 py-4">{user.last_login_at?new Date(user.last_login_at).toLocaleDateString():'Never'}</td><td className="px-5 py-4"><button disabled={busy||result.loading} className={button} aria-label={`Edit ${user.username}`} onClick={()=>{setSelected({...user});setMessage('');setError('');}}>{rolesOnly?'Edit role':'Edit'}</button></td></tr>)}</tbody></table>{result.data?.users.length===0&&<p className="p-6 text-gray-500">No users match your search.</p>}</div>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-gray-500">{result.data?.total ?? 0} users · Page {page}</p><div className="flex gap-3"><button className={button} disabled={page===1||result.loading||busy} onClick={()=>setPage(page-1)}>Previous</button><button className={button} disabled={!result.data||page*result.data.pageSize>=result.data.total||result.loading||busy} onClick={()=>setPage(page+1)}>Next</button></div></div>
  </>;
}
