import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import Navbar from "../components/Navbar";
import api from "../api/axios";

type Lesson = { id: string; title: string; allowed: boolean; reasons: string[] };
const slugs: Record<string, string> = { "japanese-n5-unit-1-hello": "n5-unit-1-hello", "japanese-n5-unit-1-introductions": "n5-unit-1-introductions", "japanese-n5-unit-1-origin": "n5-unit-1-origin", "japanese-n5-unit-1-questions": "n5-unit-1-questions", "japanese-n5-unit-1-numbers-age": "n5-unit-1-numbers-age", "japanese-n5-unit-1-demonstratives": "n5-unit-1-demonstratives" };
export default function LessonsPage() {
  const navigate = useNavigate(); const [lessons, setLessons] = useState<Lesson[]>([]);
  useEffect(() => { api.get("/lessons").then(({ data }) => setLessons(data.lessons)).catch(() => undefined); }, []);
  return <div className="min-h-screen bg-gray-50 flex flex-col"><Navbar /><main className="max-w-5xl w-full mx-auto px-4 sm:px-6 py-10 flex-1"><button onClick={() => navigate("/")} className="text-sm font-semibold text-gray-600 hover:text-gray-900">← Dashboard</button><div className="mt-6 mb-8"><span className="inline-flex bg-emerald-100 text-emerald-800 px-3 py-1 rounded-full text-xs font-bold">🇯🇵 Japanese • N5 Beginner</span><h1 className="mt-3 text-3xl sm:text-4xl font-black text-gray-900">Lessons</h1><p className="mt-2 text-gray-600">Build practical Japanese step by step.</p></div><div className="space-y-4">{lessons.map((lesson, index) => <button key={lesson.id} disabled={!lesson.allowed} onClick={() => lesson.allowed && navigate(`/lessons/japanese/${slugs[lesson.id]}`)} className={`w-full text-left bg-white rounded-3xl border shadow-sm transition p-6 sm:p-8 ${lesson.allowed ? "border-emerald-200 hover:shadow-md hover:border-emerald-400 cursor-pointer" : "border-gray-200 opacity-75 cursor-not-allowed"}`}><div className="flex flex-col sm:flex-row sm:items-center gap-5"><div className="w-14 h-14 shrink-0 rounded-2xl bg-emerald-100 text-emerald-700 flex items-center justify-center text-3xl font-bold">{index + 1}</div><div className="flex-1"><p className="text-xs font-bold tracking-wider uppercase text-emerald-700">Unit 1 • Lesson {index + 1} • 5–10 min</p><h2 className="mt-1 text-2xl font-black text-gray-900">{lesson.title}</h2><p className="mt-1 text-sm text-gray-600">{lesson.allowed ? "Ready to continue your Japanese foundations." : `🔒 Requires: ${lesson.reasons.join(" • ")}`}</p></div><span className="text-emerald-700 font-bold">{lesson.allowed ? "Start lesson →" : "Locked"}</span></div></button>)}</div></main></div>;
}
